# Generated by Django 4.1 on 2022-09-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='registration',
            name='email',
            field=models.TextField(default=None, max_length=50, verbose_name='Email юзера'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='phone',
            field=models.IntegerField(verbose_name='Телефон юзера'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID юзера'),
        ),
    ]
